/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_accueil (void);
GtkWidget* create_ajout_menu (void);
GtkWidget* create_modifier_menu (void);
GtkWidget* create_liste_menu (void);
GtkWidget* create_supprimer_menu (void);
GtkWidget* create_meilleur_menu (void);
GtkWidget* create_windowgestion (void);
GtkWidget* create_agent_de_foyer (void);
GtkWidget* create_Sign_up (void);
GtkWidget* create_window1 (void);
GtkWidget* create_Login (void);
GtkWidget* create_Admin (void);
